<?php  $gallery = $this->gallery; ?>
<div class="breadcrumbs">
    <ul>
        <li><a href="/">Strona główna</a></li>
        <li><a href="<?php echo $this->url(array(),'domain-gallery-list'); ?>">Galeria</a></li>
        <li><?php echo $gallery['Translation'][$this->language]['name']; ?></li>
    </ul>
</div>
<article id="content">
        <div class="wrapper tabs">
                <div class="tab-content" id="tab1">
                        <h5>
				<?php echo $gallery['Translation'][$this->language]['name']; ?>
			</h5>
                        <div class="wrapper pad_bot2">
                                <figure class="left marg_right1">
				    <?php if(strlen($gallery['Photos'][1])): ?>
				     <a class="lightview image-hover" href="<?php echo MF_Text::getPhotoPath($gallery['Photos'][1]); ?>"  data-lightview-type="image" data-lightview-group="<?php echo $gallery['Translation'][$this->language]['slug']; ?>" data-lightview-options="
				   width: 800,
				   height: 600,
				 " data-lightbox="lightbox" class="image-hover">
					<img src="<?php echo MF_Text::getPhotoPath($gallery['Photos'][1],'180x141'); ?>" alt="<?php echo $gallery['Translation'][$this->language]['name']; ?>" title="<?php echo $gallery['Translation'][$this->language]['name']; ?>">
				     </a>
				    <?php endif; ?>
				</figure>
                                <p class="pad_bot1"><?php echo $gallery['Translation'][$this->language]['description']; ?></p>
                                
			</div>
			<div class="photoGallery">
			    <?php foreach($gallery['Photos'] as $key => $photo):
				if($key<2)
				    continue;
				?>

			    <a class="lightview image-hover" href="/media/photos/<?php echo $photo['offset']?>/<?php echo $photo['filename'] ?>"  data-lightview-type="image" data-lightview-group="<?php echo $gallery['Translation'][$this->language]['slug']; ?>" data-lightview-options="
				   width: 800,
				   height: 600,
				 " data-lightbox="lightbox" class="image-hover">
				<img src="<?php echo MF_Text::getPhotoPath($photo,'180x141'); ?>" alt="<?php echo $gallery['Translation'][$this->language]['name']; ?>" name="<?php echo $gallery['Translation'][$this->language]['name']; ?>">
				     
			    </a>
			    <?php endforeach; ?>
			</div>
			<div class="share-article-body">
				<div class="main-title">
					<h2>Poleć znajomym</h2>
					<!--<span>Poinformuj innych o artykule</span>-->
				</div>
				<div class="">
					<a href="http://www.facebook.com/share.php?u=<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" class="share-body ot-facebook"><i class="fa fa-facebook"></i><span></span></a>
					<a href="https://twitter.com/share" class="share-body ot-twitter"><i class="fa fa-twitter"></i><span></span></a>
					<a href="https://plusone.google.com/_/+1/confirm?<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" class="share-body ot-google"><i class="fa fa-google-plus"></i><span></span></a>
					<a href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" class="share-body ot-linkedin"><i class="fa fa-linkedin"></i><span></span></a>
					<a href="http://pinterest.com/pin/create/button/?<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" class="share-body ot-pinterest"><i class="fa fa-pinterest"></i><span></span></a>
				</div>
			</div>
		</div>
    
        </div>

</article>

