<?php if(isset($this->tree)): ?>
    <ul class="clearfix">
    <?php foreach($this->tree as $item): ?>
        <li>
                <a href="<?php echo $this->url(array('slug' => $item['Translation'][$this->language]['slug']),$item['route']) ;?>"><?php echo $item->Translation[$this->language]->title; ?></a>

            <?php if($item->getNode()->getChildren()): ?>
            <?php echo $this->partial('menu-main-tree.phtml', 'default', array('subtree' => $item->getNode()->getChildren(), 'parent' => $item, 'language' => $this->language)) ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php elseif(isset($this->subtree)): ?>
        <ul class="dropdown-menu">
        <?php foreach($this->subtree as $item): ?>
            <?php if($item->Translation[$this->language]->title): ?>
            <li>
                <?php if($item['target_type'] && count($item['Articles']) > 0): ?>
                    <?php if(count($item['Articles']) < 2 && $item->Translation[$this->language]->slug): ?>
                        <a href="<?php echo $this->url(array('slug' => $item->Translation[$this->language]->slug), 'domain-i18n:article-page') ?>"><?php echo $item->Translation[$this->language]->title; ?></a>
                    <?php else: ?>
                        <a href="<?php echo $this->url(array('slug' => $item->Translation[$this->language]->slug), 'domain-i18n:article-list') ?>"><?php echo $item->Translation[$this->language]->title; ?></a>
                    <?php endif; ?>
                <?php else: ?>
                    <a href="javascript:void(0)"><?php echo $item->Translation[$this->language]->title; ?></a>
                <?php endif; ?>
                <?php if($item->getNode()->getChildren()): ?>
                <?php echo $this->partial('menu-main-tree.phtml', 'default', array('subtree' => $item->getNode()->getChildren(), 'parent' => $item, 'language' => $this->language)) ?>
                <?php else:
                        echo $item->Translation[$this->language]->slug;
                    endif; ?>
            </li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>