<?php

/**
 * League_Model_Doctrine_Team
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage League
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class League_Model_Doctrine_Team extends League_Model_Doctrine_BaseTeam
{
    public function setUp()
    {
        parent::setUp();
        
        $this->hasMany('League_Model_Doctrine_Match as Matches2', array(
             'local' => 'id',
             'foreign' => 'team2'));
        
    }
}